### ISSUE TITLE
[suggestion] Update to 2.4.7 and possibly include Hypershield?

### ISSUE THREAD

**Issue by otherguy** [ankane/blazer-docker#8]
Hi! Would you consider updating this to 2.4.7? If you could add your addon gems like [Hypershield](https://github.com/ankane/hypershield) or trend/prophet that would also be greatly appreciated :)

**Comment by ankane** [comment]
Hi @otherguy, thanks for the suggestions! I just added Trend to the image and pushed 2.4.8 (new Blazer release from earlier today). I'd like to include Prophet, but it triples the image size (~600MB to ~1800MB), so need to investigate what's going on there. I'm not sure Hypershield is a good fit for the image, since it typically needs to be installed in the Rails app that manages your database rather than the Blazer Rails app (when they're separate like they would be here).

**Comment by otherguy** [comment]
Awesome, thank you!

Regarding Hypershield, that makes perfect sense. I merely passed on a request I received without looking into how Hypershield works. In our case, Blazer is configured on a read-replica so Hypershield wouldn't work at all.

Thanks again!
