### ISSUE TITLE
Can't run using local database

### ISSUE THREAD

**Issue by strogiyotec** [ankane/blazer-docker#9]
Good day, I just pulled this image from a hub and tried to run it, however when I open localhost:8080 I don't see anything except for an empty page and bunch of 500 server errors in network tab.
 Steps to reproduce 
1. `docker pull ankane/blazer`
2. `docker run -ti -e DATABASE_URL=postgres://user:password@host.docker.internal:5432/dbname -p 8080:8080 ankane/blazer`
I assume it's trying to connect to my host machine's Postgres . I don't see anything in logs too 
```
rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
puma (5.5.2) lib/puma/configuration.rb:249:in `call'
puma (5.5.2) lib/puma/request.rb:77:in `block in handle_request'
puma (5.5.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'
puma (5.5.2) lib/puma/request.rb:76:in `handle_request'
puma (5.5.2) lib/puma/server.rb:447:in `process_client'
puma (5.5.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'

```

What could be the problem ?

**Comment by ankane** [comment]
Hey @strogiyotec, it looks like the logs above only have part of the stack trace. The rest of the logs should have the error message.

**Comment by wittawasw** [comment]
@strogiyotec The error should be in the upper part from this, try scroll up a bit.

My guess is you probably hadn't create Blazer's related tables yet since you didn't mention it. Blazer need its own tables to keep various things like queries, dashboards. Use the docker command in [Getting Started](https://github.com/ankane/blazer-docker#getting-started)
